[de]
	baseURL = "https://beta.datenanfragen.de/"

[en]
	baseURL = "https://beta.datarequests.org/"

[fr]
	baseURL = "https://www.demandetesdonnees.fr/"

[pt]
	baseURL = "https://www.pedidodedados.org/"

[es]
	baseURL = "https://www.solicituddedatos.es/"

[hr]
	baseURL = "https://www.osobnipodaci.org/"

[nl]
	baseURL = "https://www.gegevensaanvragen.nl/"
